### ISSUE TITLE
Create database models for identity

### ISSUE THREAD

**Issue by lamkeewei** [isomerpages/isomercms-backend#211]
## Description
Create database models to support managing identities through Isomer directly.

**Tasks**
- [ ] Create sequelize models for `users`, `sites` and `site_members`. Refer to the preliminary database schema below. Editable at [here](https://dbdiagram.io/d/60de823cdd6a597148291ac3).
- [ ] Setup database migrations using `sequelize-cli` to populate initial tables
- [ ] Setup infrastructure on AWS
   - Create RDS instances in private subnet
   - Setup bastion host for tunneling connection to database

![Isomer identity (2)](https://user-images.githubusercontent.com/3666479/127447514-b0a69ad4-129c-4c06-81e4-08e247b64648.png)
