### ISSUE TITLE
Middleware to inject repo-level access token for configured sites

### ISSUE THREAD

**Issue by lamkeewei** [isomerpages/isomercms-backend#212]
## Description
Execute operations on GitHub using a repo-level access token instead of the user's personal access token for routes (excluding `/sites`).

Depends on `sites` tables that will be created in #211 

**Tasks**
- [ ] Create a test repo
- [ ] Create a machine user account on GitHub and add user to repo
- [ ] Create access token for machine user account and add secret to Secrets Manager
- [ ] Create record on `sites` table, using the name of the secret in Secrets Manager for `api_token_name`.
- [ ] Implement middleware `getSiteAccessToken`. Rough logic as follows:

![getSiteAccessToken (2)](https://user-images.githubusercontent.com/3666479/125244359-d2809480-e321-11eb-8aa7-8bfbd882b94e.png)

**Other considerations**
- This creates an additional API call for each request as it needs to verify if the GitHub user has access to the site.
- We might want to maintain a local cache with TTL for previously fetched secrets. Main reasons for this is retrieving a secret from Secrets Manager has an added latency. In addition, Secrets Manager also charges based on number of operations.
