### ISSUE TITLE
Epic: Identity phase 1

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-backend#361]
Details to be updated subsequently

### Frontend [P0]
- [x] Rebase existing frontend PR https://github.com/isomerpages/isomercms-frontend/pull/559 (done)

### Backend
- [x] Rebase existing backend PR to verify that it works [P0]
- [x] Set up Twilio (details TBD) [P0]
- [x] Set up integration with Postman (details TBD) [P0]
~- [ ] Break up existing backend PR into smaller chunks [P1]~ (not done, brief writeup given for overview)
- [x] Set up local dev database [P1]
- [x] Test suite [P1]
    - [x] Unit tests
    - [x] Integration tests
- [x] Integration with API v2 endpoints [P0]

### Infra [P0]
- [x] Set up RDS cluster for staging (done) and production
    - [x] Ensure that each cluster has at least 1 writer and 1 reader instance
    - [x] Ensure that the RDS instances are in private subnets of the respective VPCs
    - [x] Ensure that the RDS instance security groups are only reachable by the backend EB security group and the bastion SSH instance
- [x] Set up bastion SSH instances using AWS EC2 for staging and production
    - [x] Ensure that the bastion SSH instances are in the public subnets of the respective VPCs
    - [x] Ensure that the bastion SSH instance security groups only has SSH ports open to our team members’ IP addresses
- [x] Update infra diagram
- [x] Set up alarms for RDS (notify Slack `isomer-monitoring` channel for both staging and prod alarms, but only OpsGenie for prod alarms)
    - [x] CPU utilization > 60%, treat missing data as bad
    - [x] Freeable memory <=250MB, treat missing data as bad
    - [x] Write latency > 5s, treat missing data as bad
    - [x] Read latency > 5s, treat missing data as bad

**Comment by seaerchin** [comment]
@alexanderleegs @prestonlimlianjie 

# TODOs for testing 
- [ ] ensure env var set up
- [ ] ensure db set up 

# dependencies 
**did keewei set this up properly or did he mock with `console.log`**
- [ ] how do we set up local twilio
- [ ] how do we set up w/ postman locally (@prestonlimlianjie)

(maybe break-up)

# testing
- [ ] unit tests for methods
- [ ] integration for services etc

**Comment by kathleenkhy** [comment]
List of domains to be whitelisted:
@tp.edu.sg
@nyp.edu.sg
@sirs.edu.sg
@moe.edu.sg
@a-star.edu.sg
@sp.edu.sg

**Comment by seaerchin** [comment]
@alexanderleegs @prestonlimlianjie 

A problem that came up during conversion to TS is that the initial identity PR had this weird constructor pattern in `identity/index.js`, where an initializer function is being exported and called by `server.js` and this sets properties on a `services` object within `index.js`

This `index.js` is then consumed downstream by auth router and auth middleware (**prior** to shifting to v2 routes), which means that htere is an implicit dependency between initialized identity services and the auth stuff.

going forward, this means that
1. #368 will have to incorporate the changes into the updated auth middleware/routers
2. the weird init stuff will be deleted from `identity/index.js` and shifted into `server.js`

**Comment by seaerchin** [comment]
Also, we should enable postman email for all email addresses. currently, only kathleen's email works.
